"""Add login tracking fields to Client

Revision ID: 06d70abd933b
Revises: 6bd6fd296303
Create Date: 2025-10-27 07:57:29.882244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d70abd933b'
down_revision: Union[str, Sequence[str], None] = '6bd6fd296303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_logged_in', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'client_id')
    op.drop_column('clients', 'last_login_time')
    op.drop_column('clients', 'is_logged_in')
    # ### end Alembic commands ###
