"""added the forgot password fields in the client

Revision ID: 2ec6691e8512
Revises: d42cbb90da41
Create Date: 2025-12-28 13:42:13.536120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec6691e8512'
down_revision: Union[str, Sequence[str], None] = 'd42cbb90da41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password_reset_token_expires')
    op.drop_column('clients', 'password_reset_token')
    # ### end Alembic commands ###
