"""almost all models of the competetor analysis added

Revision ID: 5caa06be5994
Revises: b4bea9451e9a
Create Date: 2025-12-22 13:41:02.929955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5caa06be5994'
down_revision: Union[str, Sequence[str], None] = 'b4bea9451e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_analyzed_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('extracted_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_promotional', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyzed_images_brand', 'competitor_analyzed_images', ['brand_name'], unique=False)
    op.create_index('ix_analyzed_images_source', 'competitor_analyzed_images', ['source'], unique=False)
    op.create_index(op.f('ix_competitor_analyzed_images_id'), 'competitor_analyzed_images', ['id'], unique=False)
    op.create_table('competitor_brand_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brand_offers_active', 'competitor_brand_offers', ['is_active'], unique=False)
    op.create_index('ix_brand_offers_brand', 'competitor_brand_offers', ['brand'], unique=False)
    op.create_index('ix_brand_offers_scraped_at', 'competitor_brand_offers', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_competitor_brand_offers_id'), 'competitor_brand_offers', ['id'], unique=False)
    op.create_table('competitor_business_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('price_keywords', sa.Text(), nullable=True),
    sa.Column('offer_keywords', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'business_type', name='uq_client_business_type')
    )
    op.create_index(op.f('ix_competitor_business_config_id'), 'competitor_business_config', ['id'], unique=False)
    op.create_table('competitor_daily_news_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('expert_opinion', sa.Text(), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'date', name='uq_daily_summary')
    )
    op.create_index(op.f('ix_competitor_daily_news_summaries_id'), 'competitor_daily_news_summaries', ['id'], unique=False)
    op.create_table('competitor_deep_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('research_query', sa.Text(), nullable=False),
    sa.Column('research_result', sa.Text(), nullable=False),
    sa.Column('extracted_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interaction_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_deep_research_id'), 'competitor_deep_research', ['id'], unique=False)
    op.create_index('ix_deep_research_brand', 'competitor_deep_research', ['brand_name'], unique=False)
    op.create_index('ix_deep_research_date', 'competitor_deep_research', ['created_at'], unique=False)
    op.create_table('competitor_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source_url', 'published_at', name='uq_news')
    )
    op.create_index(op.f('ix_competitor_news_id'), 'competitor_news', ['id'], unique=False)
    op.create_index('ix_news_date', 'competitor_news', ['published_at'], unique=False)
    op.create_index('ix_news_region', 'competitor_news', ['region'], unique=False)
    op.create_table('competitor_news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_categorize', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source_url', name='uq_news_source')
    )
    op.create_index(op.f('ix_competitor_news_sources_id'), 'competitor_news_sources', ['id'], unique=False)
    op.create_table('competitor_price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('karat', sa.Integer(), nullable=False),
    sa.Column('threshold_percentage', sa.Float(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_price_alerts_id'), 'competitor_price_alerts', ['id'], unique=False)
    op.create_table('competitor_tiktok_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'business_type', name='uq_tiktok_hashtags')
    )
    op.create_index(op.f('ix_competitor_tiktok_hashtags_id'), 'competitor_tiktok_hashtags', ['id'], unique=False)
    op.create_table('competitor_website_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'website_url', name='uq_website_url')
    )
    op.create_index(op.f('ix_competitor_website_accounts_id'), 'competitor_website_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_website_accounts_id'), table_name='competitor_website_accounts')
    op.drop_table('competitor_website_accounts')
    op.drop_index(op.f('ix_competitor_tiktok_hashtags_id'), table_name='competitor_tiktok_hashtags')
    op.drop_table('competitor_tiktok_hashtags')
    op.drop_index(op.f('ix_competitor_price_alerts_id'), table_name='competitor_price_alerts')
    op.drop_table('competitor_price_alerts')
    op.drop_index(op.f('ix_competitor_news_sources_id'), table_name='competitor_news_sources')
    op.drop_table('competitor_news_sources')
    op.drop_index('ix_news_region', table_name='competitor_news')
    op.drop_index('ix_news_date', table_name='competitor_news')
    op.drop_index(op.f('ix_competitor_news_id'), table_name='competitor_news')
    op.drop_table('competitor_news')
    op.drop_index('ix_deep_research_date', table_name='competitor_deep_research')
    op.drop_index('ix_deep_research_brand', table_name='competitor_deep_research')
    op.drop_index(op.f('ix_competitor_deep_research_id'), table_name='competitor_deep_research')
    op.drop_table('competitor_deep_research')
    op.drop_index(op.f('ix_competitor_daily_news_summaries_id'), table_name='competitor_daily_news_summaries')
    op.drop_table('competitor_daily_news_summaries')
    op.drop_index(op.f('ix_competitor_business_config_id'), table_name='competitor_business_config')
    op.drop_table('competitor_business_config')
    op.drop_index(op.f('ix_competitor_brand_offers_id'), table_name='competitor_brand_offers')
    op.drop_index('ix_brand_offers_scraped_at', table_name='competitor_brand_offers')
    op.drop_index('ix_brand_offers_brand', table_name='competitor_brand_offers')
    op.drop_index('ix_brand_offers_active', table_name='competitor_brand_offers')
    op.drop_table('competitor_brand_offers')
    op.drop_index(op.f('ix_competitor_analyzed_images_id'), table_name='competitor_analyzed_images')
    op.drop_index('ix_analyzed_images_source', table_name='competitor_analyzed_images')
    op.drop_index('ix_analyzed_images_brand', table_name='competitor_analyzed_images')
    op.drop_table('competitor_analyzed_images')
    # ### end Alembic commands ###
