"""added the BusinessType table

Revision ID: 696d0e30efea
Revises: b9679de0fd57
Create Date: 2025-12-29 07:02:43.323212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696d0e30efea'
down_revision: Union[str, Sequence[str], None] = 'b9679de0fd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_types_id'), 'business_types', ['id'], unique=False)
    op.create_index(op.f('ix_business_types_name'), 'business_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_types_name'), table_name='business_types')
    op.drop_index(op.f('ix_business_types_id'), table_name='business_types')
    op.drop_table('business_types')
    # ### end Alembic commands ###
