"""added the first models for competetor analysis

Revision ID: b4bea9451e9a
Revises: e4686287f67d
Create Date: 2025-12-22 12:14:20.152827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bea9451e9a'
down_revision: Union[str, Sequence[str], None] = 'e4686287f67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_gold_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('karat', sa.Integer(), nullable=False),
    sa.Column('price_per_gram', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'date', 'karat', 'source', name='uq_gold_price')
    )
    op.create_index(op.f('ix_competitor_gold_prices_id'), 'competitor_gold_prices', ['id'], unique=False)
    op.create_table('competitor_social_media_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'username', 'platform', name='uq_social_account')
    )
    op.create_index(op.f('ix_competitor_social_media_accounts_id'), 'competitor_social_media_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_social_media_accounts_id'), table_name='competitor_social_media_accounts')
    op.drop_table('competitor_social_media_accounts')
    op.drop_index(op.f('ix_competitor_gold_prices_id'), table_name='competitor_gold_prices')
    op.drop_table('competitor_gold_prices')
    # ### end Alembic commands ###
