"""optimized the tables

Revision ID: d42cbb90da41
Revises: 9e6a135417a6
Create Date: 2025-12-28 11:51:01.914220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42cbb90da41'
down_revision: Union[str, Sequence[str], None] = '9e6a135417a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_offer_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_offer_suggestions_id'), 'competitor_offer_suggestions', ['id'], unique=False)
    op.create_index('ix_offer_suggestions_client_date', 'competitor_offer_suggestions', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_offer_suggestions_date', 'competitor_offer_suggestions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offer_suggestions_date', table_name='competitor_offer_suggestions')
    op.drop_index('ix_offer_suggestions_client_date', table_name='competitor_offer_suggestions')
    op.drop_index(op.f('ix_competitor_offer_suggestions_id'), table_name='competitor_offer_suggestions')
    op.drop_table('competitor_offer_suggestions')
    # ### end Alembic commands ###
