"""phone and address added

Revision ID: d72eb5536ecb
Revises: faefb3cd7f14
Create Date: 2025-12-16 08:18:43.449606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72eb5536ecb'
down_revision: Union[str, Sequence[str], None] = 'faefb3cd7f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
